package.json

chore(package): update semver to version 5.4.1

---

package.json

Reverts maartenpaauw/portfolio#81

Revert "Update typeface-montserrat to the latest version 🚀"

---

package.json

fix(package): update bootstrap-vue to version 0.20.1

---

package.json

fix(package): update slugify to version 1.2.1

---

package.json

chore(package): update selenium-server to version 3.5.2

---

package.json

fix(package): update intersection-observer to version 0.4.2

---

package.json

fix(package): update vue-scrollto to version 2.7.7

---

package.json

fix(package): update vue-observe-visibility to version 0.2.1

---

package.json

Reverts maartenpaauw/portfolio#219

Revert "Update bootstrap-vue to the latest version 🚀"

---

package.json

chore(package): update vue-loader to version 13.3.0

---

package.json

fix(package): update vuex to version 3.0.0

---

package.json

fix(package): update vue-router to version 3.0.1

---

package.json

chore(package): update vue-template-compiler to version 2.5.2

---

package.json

chore(package): update vue-template-compiler to version 2.5.10

---

package.json

fix(package): update vue to version 2.5.10

---

package.json

fix(package): update moment to version 2.19.4

---

package.json

chore(package): update autoprefixer to version 7.2.3

---

package.json

chore(package): update copy-webpack-plugin to version 4.3.0

---

package.json

chore(package): update vue-template-compiler to version 2.5.11

---

package.json

fix(package): update bootstrap-vue to version 1.4.0

---

package.json

chore(package): update vue-loader to version 13.6.0

---

package.json

chore(package): update chromedriver to version 2.34.0

---

package.json

fix(package): update moment to version 2.20.0

---

package.json

chore(package): update vue-template-compiler to version 2.5.13

---

package.json

fix(package): update vue to version 2.5.13

---

package.json

chore(package): update @commitlint/cli to version 5.2.6

---

package.json

chore(package): update vue-loader to version 13.6.1

---

package.json

chore(package): update copy-webpack-plugin to version 4.3.1

---

package.json

fix(package): update slugify to version 1.2.8

---

package.json

chore(package): update eslint to version 4.14.0

---

package.json

chore(package): update babel-eslint to version 8.1.0

---

package.json

chore(package): update @commitlint/cli to version 5.2.8

---

package.json

chore(package): update vue-loader to version 13.6.2

---

package.json

fix(package): update slugify to version 1.2.9

---

package.json

chore(package): update autoprefixer to version 7.2.4

---

package.json

chore(package): update chromedriver to version 2.34.1

---

package.json

chore(package): update webpack-bundle-analyzer to version 2.9.2

---

package.json

chore(package): update vue-loader to version 13.7.0

---

package.json

fix(package): update bootstrap-vue to version 1.4.1

---

package.json

chore(package): update sinon to version 4.1.5

---

package.json

chore(package): update lint-staged to version 6.0.1

---

package.json

chore(package): update cross-spawn to version 6.0.3

---

package.json

chore(package): update chromedriver to version 2.35.0

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.0

---

package.json

chore(package): update vue-style-loader to version 3.1.1

---

package.json

chore(package): update eslint-plugin-html to version 4.0.2

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.1

---

package.json

chore(package): update lint-staged to version 6.1.0

---

package.json

chore(package): update lolex to version 2.3.2

---

package.json

chore(package): update vue-style-loader to version 4.0.1

---

package.json

chore(package): update webpack-bundle-analyzer to version 2.10.0

---

package.json

chore(package): update vue-loader to version 14.1.1

---

package.json

chore(package): update eslint-plugin-node to version 6.0.0

---

package.json

chore(package): update selenium-server to version 3.9.0

---

package.json

fix(package): update animate.css to version 3.6.1

---

package.json

chore(package): update selenium-server to version 3.9.1

---

package.json

chore(package): update webpack to version 3.11.0

---

package.json

chore(package): update chalk to version 2.3.1

---

package.json

fix(package): update axios to version 0.18.0

---

package.json

chore(package): update babel-eslint to version 8.2.2

---

package.json

chore(package): update lint-staged to version 7.0.0

---

package.json

chore(package): update webpack-merge to version 4.1.2

---

package.json

chore(package): update eslint-plugin-import to version 2.9.0

---

package.json

chore(package): update @commitlint/cli to version 6.1.2

---

package.json

chore(package): update sinon to version 4.4.0

---

package.json

chore(package): update webpack-bundle-analyzer to version 2.10.1

---

package.json

chore(package): update copy-webpack-plugin to version 4.4.2

---

package.json

fix(package): update vue-scrollto to version 2.9.0

---

package.json

chore(package): update webpack-bundle-analyzer to version 2.11.0

---

package.json

chore(package): update karma-webpack to version 2.0.13

---

package.json

chore(package): update copy-webpack-plugin to version 4.5.0

---

package.json

fix(package): update moment to version 2.21.0

---

package.json

chore(package): update eslint to version 4.18.2

---

package.json

chore(package): update chalk to version 2.3.2

---

package.json

chore(package): update webpack-bundle-analyzer to version 2.11.1

---

package.json

chore(package): update webpack-hot-middleware to version 2.21.1

---

package.json

chore(package): update webpack-hot-middleware to version 2.21.2

---

package.json

fix(package): update vue-scrollto to version 2.10.0

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.2

---

package.json

chore(package): update vue-loader to version 14.2.1

---

package.json

chore(package): update vue-template-compiler to version 2.5.14

---

package.json

fix(package): update vue to version 2.5.14

---

package.json

fix(package): update vue-scrollto to version 2.11.0

---

package.json

chore(package): update selenium-server to version 3.11.0

---

package.json

chore(package): update vue-template-compiler to version 2.5.16

---

package.json

fix(package): update vue to version 2.5.16

---

package.json

chore(package): update eslint to version 4.19.0

---

package.json

chore(package): update karma-webpack to version 3.0.0

---

package.json

chore(package): update autoprefixer to version 8.2.0

---

package.json

chore(package): update html-webpack-plugin to version 3.1.0

---

package.json

chore(package): update vue-loader to version 14.2.2

---

package.json

chore(package): update node-sass to version 4.8.3

---

package.json

chore(package): update chromedriver to version 2.37.0

---

build/webpack.dev.conf.js
build/webpack.prod.conf.js
package.json

Depends on:
https://github.com/maartenpaauw/portfolio/pull/651
https://github.com/maartenpaauw/portfolio/pull/589

feat(webpack): webpack 4 support

---

package.json

chore(package): update webpack to version 4.4.0

---

package.json

chore(package): update eslint-plugin-import to version 2.10.0

---

package.json

chore(package): update lint-staged to version 7.0.2

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.3

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.6

---

package.json

chore(package): update inject-loader to version 4.0.1

---

package.json

chore(package): update karma-sinon-chai to version 1.3.4

---

package.json

chore(package): update eslint-plugin-html to version 4.0.3

---

package.json

chore(package): update babel-eslint to version 8.2.3

---

package.json

chore(package): update autoprefixer to version 8.3.0

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.7

---

package.json

chore(package): update chalk to version 2.4.0

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.8

---

package.json

chore(package): update webpack-hot-middleware to version 2.22.1

---

package.json

chore(package): update node-sass to version 4.9.0

---

package.json

chore(package): update chromedriver to version 2.38.2

---

package.json

fix(package): update bootstrap-vue to version 2.0.0-rc.9

---

package.json

fix(package): update vue-analytics to version 5.10.4

---

package.json

chore(package): update @commitlint/cli to version 6.2.0

---

package.json

chore(package): update chromedriver to version 2.38.3

---

package.json

chore(package): update lint-staged to version 7.1.0
